# Generated by Django 4.2.1 on 2023-05-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.client'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.master'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.saloon'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.service'),
        ),
    ]
